GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/63567582b7003523611d7ab9
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "This note belongs to root user",
    "important": false,
    "userId": "6370daf9b965ac1a7b59db7b"
}
###
DELETE http://localhost:3001/api/notes/635bb2f8466f28ebc1478beb
###
PUT http://localhost:3001/api/notes/6372227a9509551c3afa9604
Content-Type: application/json

{
    "content": "This is a new note for a currrent user",
    "important": true
}
